#!/bin/bash

# Copyright 2010 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generates base64 versions of images so they can be inlined using the 'data:'
# URI scheme.

declare -ra IMAGE_FILES=( close.png arrow.png )

for image in ${IMAGE_FILES[@]}; do
  OUT="$image.base64"
  cat "$image" \
      | uuencode -m ignore-this \
      | grep -v begin-base64 \
      | grep -v "====" \
      | xargs echo \
      | sed -e 's/ //g' \
      | xargs echo -n \
      > $OUT
  ls -l $OUT
done
