name: "Check spelling"
on: # rebuild any PRs and main branch changes
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

permissions:
  contents: read

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: streetsidesoftware/cspell-action@e0668cf020899e887ee8ad4d173c31738a79eae8 # v9.0.1
        with:
          inline: warning
          strict: false
          incremental_files_only: true
